drop table if exists {SCHEMA}.publication_affiliation_geo
drop table if exists {SCHEMA}.all_datasets
drop table if exists {SCHEMA}.affiliation_geo
drop table if exists {SCHEMA}.snippet_validation
drop table if exists {SCHEMA}.reviewer
drop table if exists {SCHEMA}.publication_topic
drop table if exists {SCHEMA}.topic
drop table if exists {SCHEMA}.issn
drop table if exists {SCHEMA}.author_affiliation
drop table if exists {SCHEMA}.dyad_model
drop table if exists {SCHEMA}.dyad
drop table if exists {SCHEMA}.publication_asjc
drop table if exists {SCHEMA}.author_affiliation
drop table if exists {SCHEMA}.publication_author
drop table if exists {SCHEMA}.publication_affiliation
drop table if exists {SCHEMA}.publication
drop table if exists {SCHEMA}.journal
drop table if exists {SCHEMA}.publisher
drop table if exists {SCHEMA}.asjc
drop table if exists {SCHEMA}.author
drop table if exists {SCHEMA}.dataset_alias
drop table if exists {SCHEMA}.susd_user
drop table if exists {SCHEMA}.agency_run
drop table if exists {SCHEMA}.model
